# Default values for token-validator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/metal-toolbox/audito-maldito/audito-maldito
  pullPolicy: IfNotPresent
  tag: "removes-coreos-systemd-go"
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 1
    memory: 512Mi
priorityClassName: ""
metrics:
  enabled: true
health:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
