---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name:  {{ template "app.name" . }}-service-monitor
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  podMetricsEndpoints:
    - path: metrics
      scheme: http
      scrapeTimeout: 5s
      port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}